Q_Three_first:
	gcc -pthread copy.c -o copy
	./copy input_1.txt output_1.txt
	md5sum input_1.txt output_1.txt

Q_Three_second:
	gcc -pthread copy.c -o copy
	./copy input_2.txt output_2.txt
	md5sum input_2.txt output_2.txt
